server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line redirects all 404s to index.html so your frontend router works
        try_files $uri $uri/ /index.html;
    }

    # Optional: Handle the devtools error you saw
    location = /.well-known/appspecific/com.chrome.devtools.json {
        return 404;
    }
}

