"""fixing dictionary data model

Revision ID: 1cdc7ff26472
Revises: 956e9c0d955f
Create Date: 2026-03-20 03:09:06.961076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdc7ff26472'
down_revision: Union[str, Sequence[str], None] = '956e9c0d955f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_annotations', sa.Column('corrected_meaning', sa.Text(), nullable=True))
    op.drop_column('dictionary_annotations', 'corrected_translation')
    op.drop_column('dictionary_annotations', 'corrected_pronunciation')
    op.add_column('dictionary_entries', sa.Column('meaning', sa.Text(), nullable=False))
    op.create_index(op.f('ix_dictionary_entries_word'), 'dictionary_entries', ['word'], unique=False)
    op.drop_column('dictionary_entries', 'translation')
    op.drop_column('dictionary_entries', 'pronunciation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_entries', sa.Column('pronunciation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dictionary_entries', sa.Column('translation', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_dictionary_entries_word'), table_name='dictionary_entries')
    op.drop_column('dictionary_entries', 'meaning')
    op.add_column('dictionary_annotations', sa.Column('corrected_pronunciation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('dictionary_annotations', sa.Column('corrected_translation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dictionary_annotations', 'corrected_meaning')
    # ### end Alembic commands ###
