"""add dictionary_reports table

Revision ID: c4d5f7e7b2d4
Revises: ed80f6dade22
Create Date: 2026-07-06 00:14:53.711738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4d5f7e7b2d4'
down_revision: Union[str, Sequence[str], None] = 'ed80f6dade22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['dictionary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'keycloak_sub', name='uq_dictionary_report_entry_user')
    )
    op.create_index(op.f('ix_dictionary_reports_entry_id'), 'dictionary_reports', ['entry_id'], unique=False)
    op.create_index(op.f('ix_dictionary_reports_keycloak_sub'), 'dictionary_reports', ['keycloak_sub'], unique=False)
    op.drop_index(op.f('ix_email_subscriptions_email'), table_name='email_subscriptions')
    op.drop_index(op.f('ix_email_subscriptions_id'), table_name='email_subscriptions')
    op.drop_table('email_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_email_subscriptions_id'), 'email_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_email_subscriptions_email'), 'email_subscriptions', ['email'], unique=True)
    op.drop_index(op.f('ix_dictionary_reports_keycloak_sub'), table_name='dictionary_reports')
    op.drop_index(op.f('ix_dictionary_reports_entry_id'), table_name='dictionary_reports')
    op.drop_table('dictionary_reports')
    # ### end Alembic commands ###
